Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\Documents\django-project\shoply\products\views.py", line 88, in products_list
    return render(request, 'products/products.html', context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\staticfiles\storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\staticfiles\storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\staticfiles\storage.py", line 516, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for 'products/main.css'
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\Documents\django-project\shoply\products\views.py", line 88, in products_list
    return render(request, 'products/products.html', context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\staticfiles\storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\staticfiles\storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\staticfiles\storage.py", line 516, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for 'products/main.css'
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\files\storage\handler.py", line 26, in __getitem__
    return self._storages[alias]
KeyError: 'staticfiles'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\Documents\django-project\shoply\products\views.py", line 88, in products_list
    return render(request, 'products/products.html', context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\utils\functional.py", line 251, in inner
    self._setup()
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\staticfiles\storage.py", line 540, in _setup
    self._wrapped = storages[STATICFILES_STORAGE_ALIAS]
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\files\storage\handler.py", line 34, in __getitem__
    storage = self.create_storage(params)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\files\storage\handler.py", line 46, in create_storage
    return storage_cls(**options)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\whitenoise\storage.py", line 64, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\staticfiles\storage.py", line 459, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\staticfiles\storage.py", line 111, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\staticfiles\storage.py", line 29, in __init__
    check_settings(base_url)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\staticfiles\utils.py", line 49, in check_settings
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the required STATIC_URL setting.
"GET / HTTP/1.1" 500 145
